### ISSUE TITLE
Discourage or Disallow usage of yoda conditions style

### ISSUE THREAD

**Issue by mrDlef** [AlumnForce/coding-conventions#7]
See: [Add Yoda Conditions style](https://github.com/AlumnForce/coding-conventions/pull/6)

**Comment by ivanPrunier** [comment]
So are we forbidding Yoda notation totally?

**Comment by mrDlef** [comment]
I don't know. @geoffroy-aubry what do you think? We discourage or we disallow it?

As we have voted against I think we should disallow it. I let someone else do a PR.

**Comment by geoffroy-aubry** [comment]
Yes, we have voted against. So we will ban it. I will do a PR.
